version: '3'

services:
  orders-db:
    container_name: orders_database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ordersdb
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  pgdata:
    external: true


